/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'AMIT' at '12/13/15 5:51 AM' with Gradle 2.6
 *
 * @author AMIT, @date 12/13/15 5:51 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
